services:
  nginx:
    container_name: nginx
    image: nginx:latest

    ports:
      - 8080:80

    volumes:
      - ./html:/usr/share/nginx/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/defauly.conf